steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/jyotibhagat1/kucicd.git']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1-jb'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

substitutions:
    _PROJECT: searce-playground-v1
    _ZONE: us-central1-c
    _GKE_CLUSTER: cluster-1-jb

    _DEPLOYMENTNAME: httpd3
    _CONTAINERNAME: jyotibrepo
    _REPO_NAME: kucicd
    
    _VERSION: version1

options:
    substitution_option: 'ALLOW_LOOSE'

