apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: httpd3
  name: httpd3
spec:
  replicas: 2
  selector:
    matchLabels:
      run: httpd3
  template:
    metadata:
      labels:
        run: httpd3
    spec:
      containers:
      - image: gcr.io/searce-playground-v1/jyotibrepo
        name: jyotibrepo
        ports:
        - containerPort: 80
